config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :documents, except: %i[show edit update]
  get 'profile', to: 'pages#profile', as: 'profile'
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  validates :category, presence: true
  validates :category, uniqueness: { scope: :user }
  validates :category, inclusion: { in: ['Identidade', 'Habilitação', 'Documento do Veículo',
                                         'Carteira de Vacinação', 'Passaporte', 'Título de Eleitor', 'Outros'] }
  has_one_attached :front
  has_one_attached :back

  def renew_in_days
    (renew_date - Date.current).to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :documents, dependent: :destroy
  has_one_attached :avatar
  validates :first_name, :last_name, :email, :birthday, :cpf, :genre, presence: true
  validates :cpf, uniqueness: true
  validates :genre, inclusion: { in: ['Masculino', 'Feminino'] }
  validate :validate_cpf
  validates :validate_cpf, length: { maximum: 14 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def validate_cpf
    errors.add(:cpf, "Inválido") unless cpf.valid_cpf?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name birthday cpf genre])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name birthday])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index]

  def index
    @documents = policy_scope(Document).order(created_at: :desc)
    @documents = Document.where(user: current_user)
    authorize @documents
  end

  def new
    @document = Document.new
    authorize @document
  end

  def create
    @document = Document.new(document_params)
    @document.user = current_user

    authorize @document

    if @document.save
      redirect_to documents_path(@document)
    else
      render :new
    end
  end

  # def edit
  #   @document = Document.find(params[:id])
  #   authorize @document
  # end

  # def update
  #   @document = Document.find(params[:id])
  #   authorize @document
  #   if @document.update(document_params)
  #     redirect_to @document, notice: 'Seu documento foi atualizado!'
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path(@document)
    authorize @document
  end

  # def show
  #   @document = Document.find(params[:id])
  #   authorize @document
  # end

  private

  def document_params
    params.require(:document).permit(:category, :renewal, :renew_date, :user_id, :front, :back)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/edit.html.erb
<div class=" container-login col-sm-8 text-center container-new-document">
  <div class="card-login">
    <%= simple_form_for @document do |f| %>
      <div class="form-inputs mt-4 col-md-6 offset-md-3" data-controller="renewal datepicker">
        <%= f.input :category, collection: ['Identidade', 'Habilitação', 'Documento do Veículo',
                                         'Carteira de Vacinação', 'Passaporte', 'Título de Eleitor', 'Outros'],
                                         label: "Categoria do Documento" %>
        <%= f.input :renewal, as: :boolean, label: "Documento tem validade?", input_html: { data: { action: "change->renewal#showRenewalDate" } } %>
        <% if @document.renewal %>
          <%= f.input :renew_date, as: :string, required: false, label: "Data de vencimento", input_html: { class: "datepicker" } %>
        <% else %>
          <div class="d-none" data-renewal-target="renewalDate" >
            <%= f.input :renew_date, as: :string, required: false, label: "Data de vencimento", input_html: { class: "datepicker" } %>
          </div>
        <% end %>
        <%= f.input :front, label: "Anexar frente do documento", as: :file %>
        <%= f.input :back, label: "Anexar verso do documento", as: :file %>
        <div class="form-actions">
          <%= f.button :submit, 'Salvar alteração', class: 'mt-3 btn-registrar' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script defer src="https://cdn.crop.guide/loader/l.js?c=FGSGVY"></script>

app/views/documents/index.html.erb
<div class="container container-index"  >
  <div class="document-content">
    <h1>Meus documentos</h1>
    <div class="document-grid">
      <div class="grid-item">
        <% if @documents.length != 0 %>
          <% @documents.each do |document| %>
            <button type="button" class="btn-document" data-bs-toggle="modal" data-bs-target="#document-<%= document.id %>">
              <h4><%= document.category %></h4>
              <i class="fas fa-address-card"></i>
              <% if document.renewal && document.renew_date %>
                <% if document.renew_in_days < 0 %>
                  <p class= "text-danger"><strong>DOCUMENTO VENCIDO DIA: <%= document.renew_date.strftime("%d/%m/%Y") %></strong></p>
                <% elsif document.renew_in_days < 90 %>
                  <p>Vence em: <span class="text-warning"><%= document.renew_in_days %> dias</span></p>
                <% else %>
                  <p>Vence em: <span class="text-success"><%= document.renew_in_days %> dias</span></p>
                <% end %>
              <% end %>
            </button>
            <div class="content-trash">
              <%= link_to document_path(document), method: :delete, data: { confirm: "Tem certeza que deseja excluir #{document.category}?" }, class: "trash" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="document-<%= document.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" ></button>
                  </div>
                  <div class="modal-body" data-controller="slider" data-slider-id-value="<%= document.id %>">
                    <div class="my-slider-<%= document.id %> " >
                      <% if document.front.attached? %>
                        <div class="img-content">
                          <%= cl_image_tag(document.front.key, :crop=>"lfill") %>
                        </div>
                      <% end %>
                      <% if document.back.attached? %>
                        <div class="img-content">
                          <%= cl_image_tag(document.back.key,  :crop=>"lfill")  %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="add-content">
              <%= link_to new_document_path, class:"add-button" do  %>
                <i class="fas fa-plus"></i>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="no-document-message">
            <h3>Você ainda não possui nenhum documento cadastrado.😢</h3>
          </div>
          <div class="add-content-new">
            <%= link_to new_document_path, class:"add-button" do  %>
              <i class="fas fa-plus"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/documents/new.html.erb
<div class=" container-login col-sm-8 text-center container-new-document">
  <div class="card-login">
    <%= simple_form_for @document do |f| %>
      <div class="form-inputs mt-4 col-12" data-controller="renewal datepicker">
        <%= f.input :category, collection: ['Identidade', 'Habilitação', 'Documento do Veículo',
                                         'Carteira de Vacinação', 'Passaporte', 'Título de Eleitor', 'Outros'],
                                         label: "Categoria do Documento",
                                         selected: 'Identidade' %>
          <%= f.input :renewal, as: :boolean, label: "Documento tem validade?", input_html: { data: { action: "change->renewal#showRenewalDate" } } %>
        <div class="d-none" data-renewal-target="renewalDate" >
          <%= f.input :renew_date, as: :string, required: false, label: "Data de vencimento", input_html: { class: "datepicker" } %>
        </div>
        <%= f.input :front, label: "Anexar frente do documento", as: :file %>
        <%= f.input :back, label: "Anexar verso do documento", as: :file %>
        <div class="form-actions">
          <%= f.button :submit, 'Cadastre seu documento', class: 'mt-3 btn-registrar btn-registro' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script defer src="https://cdn.crop.guide/loader/l.js?c=YMSBGH"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Wallet - Documentos organizados!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Igor Martins, Lidia Setubal, Mateus Bittencourt and Thiago Aragao">
    <meta property="og:title" content="Smart Wallet - Documentos organizados!">
    <meta property="og:description" content="Documentos organizados e em um só lugar!">
    <meta property="og:type" content="website">
    <meta property=”og:url” content=”https://www.smart-wallet.me”/>
    <meta property="og:image" content='https://i.imgur.com/Xxij2Yv.png' />
    <meta property="og:image:alt" content='Smart Wallet - Documentos organizados!' />
    <meta property="og:image:width" content='1200' />
    <meta property="og:image:height" content='630' />
    <meta name="twitter:image:src" content='https://i.imgur.com/Xxij2Yv.png' />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.4/tiny-slider.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css">
  </head>
  <body>
    <div class="container-wrapper">
      <%= yield %>
      <% if user_signed_in? %>
        <%= render 'shared/navbar' %>
      <% end %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="header">
  <!--Content before waves-->
  <div class="inner-header flex">
    <h1>Smart Wallet</h1>
    <% if user_signed_in? %>
      <h2>Bem Vindo</h2>
      <h3><%= current_user.first_name %> <%= current_user.last_name %> :D</h3>
      <a href="#faq"><i class="fas fa-angle-down seta"></i></a>
    <% else %>
      <p class="home-text">Documentos organizados e em um só lugar!</p>
      <a href="#faq"><i class="fas fa-angle-down seta"></i></a>
    <% end %>
  </div>
  <!--Waves Container-->
  <div>
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
      <defs>
        <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
      </defs>
      <g class="parallax">
        <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
        <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
        <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
        <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
      </g>
    </svg>
  </div>
  <!--Waves end-->
</div>
<!--Header ends-->
<!--Content starts-->
<% if !user_signed_in? %>
  <div class="home-buttons"><%= link_to "Entrar", new_user_session_path, class:"btn-entrar" %>
    <%= link_to "Cadastrar", new_user_registration_path, class:"btn-entrar" %> </div>
<% end %>
<h5 class="text-center mt-5" id="faq"><strong>Perguntas Frequentes:</strong></h5>
<div class="accordion accordion-flush accordion-margin" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
        Quem fez esse projeto?
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <div class="team-pictures accordion-body">
        <a href="https://github.com/igordmartins" target="_blank"><%= image_tag "igor.png", class: "rounded-circle" %></a>
        <a href="https://github.com/LidiaSetubal" target="_blank"><%= image_tag "lidia.png", class: "rounded-circle"%></a>
        <a href="https://github.com/Mateus-Bittencourt" target="_blank"><%= image_tag "mateus.png", class: "rounded-circle" %></a>
        <a href="https://github.com/thiagohoaragao/" target="_blank"><%= image_tag "thiago.png", class: "rounded-circle" %></a>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
        Quantas linhas de codigo?
      </button>
    </h2>
    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">Total de 2855 linhas de código!</div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
        Quais linguagens foram utilizadas?
      </button>
    </h2>
    <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <li class="languages-list">
          <i class="devicon-ruby-plain-wordmark colored"></i>  62.2%
          <i class="devicon-html5-plain-wordmark colored"></i> 22.1%
          <i class="devicon-sass-original colored"></i>10.8%
          <i class="devicon-javascript-plain colored"></i> 4.9%
        </li>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
        Quantas horas demorou?
      </button>
    </h2>
    <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">2 semanas!</div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingFive">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFive" aria-expanded="false" aria-controls="flush-collapseFive">
        Onde foi desenvoldio a Smart Wallet?
      </button>
    </h2>
    <div id="flush-collapseFive" class="accordion-collapse collapse" aria-labelledby="flush-headingFive" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">Durante o bootcamp da Le Wagon São Paulo (Batch#898) Full-Time!</div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container-perfil col-sm-8 text-center">
  <div class="card-perfil py-4">
    <div class="profile-image d-flex flex-column justify-content-center align-items-center">
      <% if current_user.genre == "Masculino" %>
        <%= image_tag("profile-male.png", height: 100, width: 100) %>
      <% else %>
        <%= image_tag("profile-female.png", height: 100, width: 100) %>
      <% end %>
      <div class="profile-icons mt-4">
        <div class="content-icon"><i class="profile-icon fas fa-user"></i></div>
        <div><span class="profile-input name mt-3"><%= current_user.first_name %> <%= current_user.last_name %></span></div>
      </div>
      <div class="profile-icons mt-3">
          <div class="content-icon"><i class="profile-icon fas fa-birthday-cake"></i></div>
        <div><span class="profile-input name mt-3"><%= current_user.birthday.strftime("%d/%m/%Y") %></span></div>
      </div>
      <div class="profile-icons mt-3">
        <div class="content-icon"><i class="profile-icon far fa-envelope"></i></div>
        <div><span class="profile-input name mt-3"><%= current_user.email %></span></div>
      </div>
      <div class="d-flex flex-row justify-content-center align-items-center mt-3">
        <div class=" d-flex mt-5"> <%= link_to "Editar Perfil", edit_user_registration_path, class:"btn-profile" %> </div>
      </div>
      <%= link_to "Sair", destroy_user_session_path, method: :delete, data: { confirm: "Você quer mesmo sair da sua conta?" }, class:"btn-sair" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-smart-wallet">
  <div class="navbar-links">
    <div class="home-icon">
      <%= link_to root_path do  %>
        <i class="fas fa-home"></i>
      <% end %>
    </div>
    <div class="wallet-icon">
      <%= link_to documents_path do  %>
        <i class="fas fa-wallet wallet-font"></i>
      <% end %>
    </div>
    <div class="user-icon">
      <%= link_to profile_path do  %>
        <i class="fas fa-user"></i>
      <% end %>
    </div>
  </div>
</div>